Controllers/ComicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;

namespace SachOnline.Controllers
{
    public class ComicController : Controller
    {
        private dbSachOnlineDataContext data;

        public ComicController()
        {
            string connection = @"Data Source=LAPTOP-7HTVH7CG\SQLEXPRESS;
                                  Initial Catalog=SachOnline;
                                  Integrated Security=True;
                                  Encrypt=False;";
            data = new dbSachOnlineDataContext(connection);
        }

        public ActionResult Index()
        {
            var list = data.TruyenTranhs.OrderByDescending(t => t.NgayCapNhat).ToList();
            return View(list);
        }

        public ActionResult ChiTiet(int id)
        {
            var truyen = data.TruyenTranhs.SingleOrDefault(t => t.MaTruyen == id);
            var chapters = data.Chapters.Where(c => c.MaTruyen == id).OrderBy(c => c.STT).ToList();
            ViewBag.Chapters = chapters;
            return View(truyen);
        }

        public ActionResult DocChapter(int id)
        {
            var chapter = data.Chapters.SingleOrDefault(c => c.MaChapter == id);

            // Lấy danh sách trang truyện, sắp xếp theo STT
            var pages = data.TrangTruyens
                .Where(p => p.MaChapter == id)
                .OrderBy(p => p.STT)
                .ToList();

            // Chuẩn hóa đường dẫn ảnh nếu cần (nếu trong DB bạn lưu chỉ tên file, không có /Image/)
            foreach (var page in pages)
            {
                if (!string.IsNullOrEmpty(page.HinhAnh) && !page.HinhAnh.StartsWith("/Image/"))
                {
                    page.HinhAnh = "/Image/" + page.HinhAnh;
                }
            }

            ViewBag.Pages = pages;

            return View(chapter);
        }

    }

}

Controllers/ReadBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;

namespace SachOnline.Controllers
{
    public class ReadBookController : Controller
    {
        private string connection;
        private dbSachOnlineDataContext data;

        public ReadBookController()
        {
            // Khởi tạo chuỗi kết nối
            connection = @"Data Source=LAPTOP-7HTVH7CG\SQLEXPRESS;
                          Initial Catalog=SachOnline;
                          Integrated Security=True;
                          Encrypt=False;";
            data = new dbSachOnlineDataContext(connection);
        }

        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes
                       .Where(s => s.MienPhi.HasValue && s.MienPhi.Value) // Lọc sách miễn phí
                       .OrderByDescending(a => a.NgayCapNhat)
                       .Take(count)
                       .ToList();
        }

        // Trang danh sách sách mới
        public ActionResult Index()
        {
            var listSachMoi = LaySachMoi(6);
            return View(listSachMoi);
        }

        // Hiển thị chi tiết sách
        public ActionResult ChiTietSach(int id)
        {
            var sach = data.SACHes.SingleOrDefault(s => s.MaSach == id);
            if (sach == null)
            {
                return HttpNotFound();
            }

            // Ghi nhận lịch sử đọc sách
            ThemLichSu(id);

            return View(sach);
        }

        // Phương thức tự động lưu sách vào lịch sử đọc
        private void ThemLichSu(int maSach)
        {
            int? maKH = Session["MaKH"] as int?;
            if (maKH == null)
            {
                return; // Nếu chưa đăng nhập, không lưu vào lịch sử
            }

            var lichSuMoi = new LichSuDocSach
            {
                MaKH = maKH.Value,
                MaSach = maSach,
                ThoiGianDoc = DateTime.Now
            };

            data.LichSuDocSaches.InsertOnSubmit(lichSuMoi);
            data.SubmitChanges();
        }

        // Các trang nội dung riêng lẻ
        public ActionResult QuanKhuNamDong() { return View(); }
        public ActionResult ConHoang() { return View(); }
        public ActionResult ChiecNgaiVang() { return View(); }
        public ActionResult TuoiThoDuDoi() { return View(); }
        public ActionResult CuocDoiNgoaiCua() { return View(); }
        public ActionResult ChiEmKhacMe() { return View(); }
    }
}

Controllers/SachOnlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        // GET: SachOnline
        private string connection;
        private dbSachOnlineDataContext data;
        public SachOnlineController()
        {
            // Khởi tạo chuỗi kết nối
            connection = @"Data Source=LAPTOP-7HTVH7CG\SQLEXPRESS;
                      Initial Catalog=SachOnline;
                      Integrated Security=True;
                      Encrypt=False;";
            data = new dbSachOnlineDataContext(connection);
        }
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        private List<SACH> LayTenChuDe(int iMaCD)
        {
            return data.SACHes.Where(s => s.MaCD == iMaCD).ToList();
        }
        private List<SACH> LayTenNXB(int iMaNXB)
        {
            return data.SACHes.Where(s => s.MaNXB == iMaNXB).ToList();
        }
        public ActionResult Index()
        {
                //Lay 6 quyen sach moi
                var listSachMoi = LaySachMoi(8);
                return View(listSachMoi);
        }
        public ActionResult Index2()
        {
            //Lay 6 quyen sach moi
            var listSachMoi = LaySachMoi(8);
            return View(listSachMoi);
        }
        public ActionResult ChuDePartial()
        {
            var listChuDe = from cd in data.CHUDEs select cd; 
            return PartialView(listChuDe);
        }
        public ActionResult NhaXuatBanPartial()
        {
            var listNhaXuatBan = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(listNhaXuatBan);
        }
        public ActionResult SachTheoChuDe(int id, int ? page)
        {
            int pageSize = 4;
            int pageNumber = page ?? 1;

            var sach = data.SACHes.Where(s => s.MaCD == id)
                                  .OrderByDescending(s => s.NgayCapNhat)
                                  .ToPagedList(pageNumber, pageSize);

            ViewBag.Id = id;
            ViewBag.ten = LayTenChuDe(id);

            return View(sach);
        }
        public ActionResult SachTheoNhaXuatBan(int id, int ? page)
        {
            int pageSize = 3;
            int pageNumber = page ?? 1;

            var sach = data.SACHes.Where(s => s.MaNXB == id)
                                  .OrderByDescending(s => s.NgayCapNhat)
                                  .ToPagedList(pageNumber, pageSize);

            ViewBag.Id = id;
            ViewBag.ten = LayTenNXB(id);

            return View(sach);
        }
        public ActionResult ChiTietSach(int id)
        {
            var sach = data.SACHes.Where(s => s.MaSach == id).SingleOrDefault();

            if (sach != null)
            {
                var binhLuans = data.Comments.Where(b => b.MaSach == id).ToList();
                var binhLuansModel = binhLuans.Select(c => new CommentModel
                {
                    IdBinhLuan = c.idBinhLuan,
                    UserName = c.UserName,
                    NoiDung = c.NoiDung,
                    NgayTao = (DateTime)c.NgayTao
                }).ToList();

                // Chuyển thông tin sách và bình luận đến View
                var chiTietModel = new ChiTietSachModel
                {
                    Sach = sach,
                    BinhLuans = binhLuansModel
                };

                return View(chiTietModel);
            }
            else
            {
                // Xử lý sách không tồn tại
                return HttpNotFound();
            }
        }
        
        public ActionResult Contact()
        {
          
            return View();
        }
        public ActionResult Details(int id)
        {
            var khachhang = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (khachhang == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(khachhang);
        }
        public ActionResult BinhLuan(int id)
        {
            var comments = data.Comments.Where(c => c.MaSach == id).ToList();
            return View(comments);
        }
        [HttpPost]
        public ActionResult ThemBinhLuan(int MaSach, string NoiDung)
        {
            // Kiểm tra xem nội dung bình luận có rỗng không, nếu rỗng thì không thêm vào cơ sở dữ liệu
            if (string.IsNullOrEmpty(NoiDung))
            {
                // Xử lý thông báo hoặc chuyển hướng về trang chi tiết sách với thông báo lỗi
                return RedirectToAction("ChiTietSach", new { id = MaSach, loi = "Nội dung bình luận không được để trống." });
            }

            // Tạo một đối tượng BinhLuan mới
            var newComment = new Comment
            {
                UserName = "Khách", // Gán tên người dùng là "Khách" hoặc tùy chọn khác
                NoiDung = NoiDung,
                NgayTao = DateTime.Now,
                MaSach = MaSach // ID của sách đang được xem chi tiết
            };

            // Thêm bình luận vào cơ sở dữ liệu
            data.Comments.InsertOnSubmit(newComment);
            data.SubmitChanges();

            // Chuyển hướng về trang chi tiết sách
            return RedirectToAction("ChiTietSach", new { id = MaSach });
        }
    }
}

Views/Shared/ChuDePartial.cshtml
@model IEnumerable<SachOnline.Models.CHUDE>
<ul class="currency_selection">

   
    @foreach (var item in Model)
    {
<li><a href="@Url.Action("SachTheoChuDe","SachOnline", new { id = item.MaCD})">@item.TenChuDe</a></li>
    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Content/master.css" />
    <link rel="stylesheet" type="text/css" media="screen,projection" href="~/Content/ie-win.css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="https://kit.fontawesome.com/0f43c8a3b4.js" crossorigin="anonymous"></script>
    <style type="text/css">
        .dangkydangnhap {
            background-color: black;
            width: 300px;
            float: right;
        }

        .cainaymoidung {
            display: flex;
            justify-content: space-around;
            margin: 0;
        }

        #header {
            height: 35px;
            background-color: black;
        }

        .dangky:hover {
            color: red;
        }

        .number {
            color: white;
            text-decoration: none;
            cursor: none;
        }

        .icDienThoai {
            width: 50%;
        }

        div.txtTimKiemall {
            height: 30px;
            float: right;
            margin-right: 30px;
            margin-top: 8px;
            width: 300px;
        }

        .btnlink button:hover {
            background-color: red;
        }

        #navigation {
            position: relative;
        }

        .imgbook {
            width: 100px;
        }

            .imgbook:hover {
                transform: scale(0,9);
                cursor: pointer;
            }

        .imgsachbannhieu {
            width: 100px;
        }

        .list-group {
            display: block;
            width: auto;
        }

        .menu {
            padding-top: 70px;
            width: 330px;
            float: left;
        }

        .tes {
            background-color: red;
        }

        .navbar {
            height: 40px;
            background-image: linear-gradient(0, red, orange);
            margin-bottom: 0px;
        }

        .grid {
            width: 1200px;
            max-width: 100%;
            margin: 0 auto;
            display: flex;
        }

        .khoangcach {
            margin: 0 auto;
            color: black;
            font-weight: 300;
        }

        .header__navbar-item {
            position: relative;
            list-style: none;
        }
    </style>
</head>
<body>
    <div id="header">
        <div class="dangkydangnhap">
            <ul class="cainaymoidung">
                <li class="header__navbar-item">@Html.Action("LoginLogoutPartial", "User")</li>
            </ul>
        </div>
    </div>
    <div id="navigation" style="height: 40px;">
        <div class="txtTimKiemall" style=" margin-right: 30px; margin-top: 8px; width:300px;">
            @using (Html.BeginForm())
            {
                @Html.TextBox("txttimkiem", "", htmlAttributes: new { @style = "height: 30px; width:300px", @placeholder = "Nhập vào từ khóa cần tìm" })
            }
            <a href="" class="header__navbar-list-link">
                <i class="fa-solid fa-magnifying-glass fa-xl" style="display:block; position: absolute; right: 2px;
bottom:17px;"></i>
            </a>
        </div>
        <ul>
            <li class="active"><a class="noibathover" href="/">Trang chủ</a></li>
            <li><a class="noibathover" href="#showcase/commercial_templates/">Liên hệ</a></li>
            <li><a class="noibathover" href="#contact/">Sách</a></li>
            <li class="noibathover">@Html.Action("GioHangPartial", "GioHang")</li>
        </ul>
    </div>
    <div class="menu">
        @Html.Action("ChuDePartial", "SachOnline")
        @Html.Action("NhaXuatBanPartial", "SachOnline")
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
        @RenderBody()
    </div>
    <!--<div id="content-wrapper">
        <div id="content">
            <p><a href="#" class="drop-shadow"><img src="~/images/the_mephisto_club.jpg" width="100" height="150" alt="the mephisto club by tess gerritsen" class="captionated" /></a></p>
            <p><a href="#" class="drop-shadow"><img src="~/images/dark_celebration.jpg" width="100" height="150" alt="dark celebration by christine freehan" class="captionated" /></a></p>
            <p><a href="#" class="drop-shadow"><img src="~/images/ricochet.jpg" width="100" height="150" alt="ricochet by sandra brown" class="captionated" /></a></p>
            <p><a href="#" class="drop-shadow"><img src="~/images/echo_park.jpg" width="100" height="150" alt="echo park by michael connelly" class="captionated" /></a></p>
            <hr />
            <p><a href="#" class="drop-shadow"><img src="~/images/the_world_is_flat.jpg" width="100" height="150" alt="the world is flat by thomas l. friedman" class="captionated" /></a></p>
            <p><a href="#" class="drop-shadow"><img src="~/images/act_of_treason.jpg" width="100" height="150" alt="act of treason by vince flynn" class="captionated" /></a></p>
            <p><a href="#" class="drop-shadow"><img src="~/images/rich_dad_poor_dad.jpg" width="100" height="150" alt="rich dad, poor dad" class="captionated" /></a></p>
            <p><a href="#" class="drop-shadow"><img src="~/images/freakonomics.jpg" width="100" height="150" alt="freakonomics" class="captionated" /></a></p>
        </div>
    </div>-->
    <div id="footer">
        <div id="meta">
            <div class="recent">
                <h3>Recently Reviewed</h3>
                <ul>
                    <li><a href="#">300 by Frank Miller</a></li>
                    <li><a href="#">A Big Fat Supernatural Wedding by Sherrilyn Kenyon</a></li>
                    <li><a href="#">Strange Candy by Laurell K. Hamilton</a></li>
                    <li><a href="#">The Time Traveler's Wife by Audrey Niffenegger</a></li>
                    <li><a href="#">Wicked by Gregory Maguire</a></li>
                    <li><a href="#">The Ice Dragon by George R. R. Martin</a></li>
                    <li><a href="#">Path of destruction by Drew Karpshyn</a></li>
                    <li><a href="#">Grave Surprise by Charlaine Harris</a></li>
                    <li><a href="#">Fahrenheit 451 by Ray Bradbury</a></li>
                    <li><a href="#">The Absolute Sandman by Neil Gaiman</a></li>
                </ul>
            </div>
            <div class="upcoming">
                <h3>To Be Read Still</h3>
                <ul>
                    <li><a href="#">The Mephisto Club by Tess Gerritsen</a></li>
                    <li><a href="#">The Husband by Dean Koontz</a></li>
                    <li><a href="#">The DaVinci Code by Dan Brown</a></li>
                    <li><a href="#">Angels Fall by Nora Roberts</a></li>
                    <li><a href="#">Twelve Sharp by Janet Evanovich</a></li>
                    <li><a href="#">Imperium by Robert Harris</a></li>
                    <li><a href="#">Under Orders by Dick Francis</a></li>
                    <li><a href="#">The Memory Keeper's Daughter by Kim Ewards</a></li>
                    <li><a href="#">Act of Treason by Vince Flynn</a></li>
                    <li><a href="#">The Collectors by David Baldacci</a></li>
                </ul>
            </div>
            <div class="authors">
                <h3>Favorite Authors</h3>
                <ul>
                    <li><a href="#">Nhà xuất bản Trẻ</a></li>
                    <li><a href="#">NXB thống kê</a></li>
                    <li><a href="#">Kim đồng</a></li>
                    <li><a href="#">Đại học quốc gia</a></li>
                    <li><a href="#">Văn hóa nghệ thuật</a></li>
                    <li><a href="#">Văn hóa</a></li>
                    <li><a href="#">Lao động - Xã hội</a></li>
                    <li><a href="#">Khoa học & Kỹ thuật</a></li>

                </ul>
            </div>
            <hr />
        </div>
        <div id="copyright"> Design copyright &copy; 2006 <a href="http://www.nikhedonia.com/" title="SimplyGold">Sadhana Ganapathiraju</a> | <a href="#showcase/free_templates/" title="More Free Templates">Free Templates</a> | <a href="#showcase/commercial_templates/" title="More Commercial Templates">Commercial Templates</a> | <a href="http://validator.w3.org/check/referer" title="Xhtml 1.1 Strict">Xhtml Happy</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Css 2.0 Strict">Css Happy</a> </div>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>ReBook</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Colo Shop Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/newcss/styles/bootstrap4/bootstrap.min.css">
    <link href="~/Content/newcss/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/Content/newcss/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/newcss/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/Content/newcss/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/newcss/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/Content/newcss/styles/responsive.css">
</head>

<body>

    <div class="super_container" style="background-color: white;">

        <!-- Header -->

        <header class="header trans_300">

            <!-- Top Navigation -->

            <div class="top_nav">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="top_nav_left">Miễn Ship Trên Toàn Việt Nam Nếu hóa Đơn trên 500k</div>
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="top_nav_right">
                                <ul class="top_nav_menu">

                                    <!-- Currency / Language / My Account -->

                                    <li class="currency">
                                        <a href="#" style="color: red;">
                                            SÁCH THEO CHỦ ĐỀ
                                            <i class="fa fa-angle-down"></i>
                                        </a>
                                        
                                            @Html.Action("ChuDePartial", "SachOnline")
                                        
                                    </li>
                                    <li class="language">
                                        <a href="#" style="color: red;" >
                                            SÁCH THEO NHÀ XUẤT BẢN
                                            <i class="fa fa-angle-down"></i>
                                        </a>
                                        @Html.Action("NhaXuatBanPartial", "SachOnline")
                                    </li>
                                    <li class="account">
                                        <a href="#">
                                            My Account
                                            <i class="fa fa-angle-down"></i>
                                        </a>
                                        <ul class="account_selection">
                                            <li>@Html.Action("LoginLogoutPartial", "User")</li>
                                         
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main Navigation -->

            <div class="main_nav_container">
                <div class="container" style="margin: 0 20%">
                    <div class="row">
                        <div class="col-lg-12 text-right">
                            <div class="logo_container">
                                <a href="@Url.Action("Index2", "SachOnline")">TDT<span>Book</span></a>
                            </div>
                            <nav class="navbar">
                                <ul class="navbar_menu">
                                    <li><a href="@Url.Action("Index", "Comic")">Truyện Tranh</a></li>
                                    <li><a href="@Url.Action("Index2", "SachOnline")">Trang chủ</a></li>

                                    <li><a href="@Url.Action("Contact", "SachOnline")">Liên hệ</a></li>
                                    <li><a href="@Url.Action("Index", "ReadBook")">Đọc Sách</a></li>
                                </ul>
                                <ul class="navbar_user">
                                    <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                                    <li><a href="@Url.Action("UserProfile", "User")"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                                    <li><a href="@Url.Action("Login", "Home", new { area = "Admin" })"><i class="fa fa-user" aria-hidden="true" style="color:red;"></i></a></li>
                                    <li class="checkout">
                                        <a href="@Url.Action("GioHang", "GioHang")">
                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                            @Html.Action("GioHangPartial", "GioHang")
                                        </a>
                                    </li>
                                </ul>
                                <div class="hamburger_container">
                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

        </header>

        <div class="fs_menu_overlay"></div>
        <div class="hamburger_menu">
            <div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
            <div class="hamburger_menu_content text-right">
                <ul class="menu_top_nav">
                    <li class="menu_item has-children">
                        <a href="#">
                            usd
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="menu_selection">
                            <li><a href="#">cad</a></li>
                            <li><a href="#">aud</a></li>
                            <li><a href="#">eur</a></li>
                            <li><a href="#">gbp</a></li>
                        </ul>
                    </li>
                    <li class="menu_item has-children">
                        <a href="#">
                            English
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="menu_selection">
                            <li><a href="#">French</a></li>
                            <li><a href="#">Italian</a></li>
                            <li><a href="#">German</a></li>
                            <li><a href="#">Spanish</a></li>
                        </ul>
                    </li>
                    <li class="menu_item has-children">
                        <a href="#">
                            My Account
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="menu_selection">
                            <li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
                            <li><a href="#"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
                        </ul>
                    </li>
                    <li class="menu_item"><a href="#">home</a></li>
                    <li class="menu_item"><a href="#">shop</a></li>
                    <li class="menu_item"><a href="#">promotion</a></li>
                    <li class="menu_item"><a href="#">pages</a></li>
                    <li class="menu_item"><a href="#">blog</a></li>
                    <li class="menu_item"><a href="#">contact</a></li>
                </ul>
            </div>
        </div>

        <div class="container">
            @RenderBody()
        </div>

        <!-- Footer -->

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
                            <ul class="footer_nav">
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">FAQs</a></li>
                                <li><a href="contact.html">Contact us</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
                            <ul>
                                <li><a href="https://www.facebook.com/profile.php?id=100014836657131"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer_nav_container">
                            <div class="cr">©2018 All Rights Reserverd. Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#">Colorlib</a> &amp; distributed by <a href="https://themewagon.com">ThemeWagon</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>

    <script src="~/Content/newcss/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/newcss/styles/bootstrap4/popper.js"></script>
    <script src="~/Content/newcss/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="~/Content/newcss/plugins/Isotope/isotope.pkgd.min.js"></script>
    <script src="~/Content/newcss/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="~/Content/newcss/plugins/easing/easing.js"></script>
    <script src="~/Content/newcss/js/custom.js"></script>
</body>

</html>